vp:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
  # Script will wait until membersrvc is up (if it exists) before starting
  # $$GOPATH (double dollar) required to prevent docker-compose doing its own
  # substitution before the value gets to the container
  command: sh -c "exec $$GOPATH/src/github.com/hyperledger/fabric/bddtests/scripts/start-peer.sh"
  # Ideally we'd only mount /var/run/docker.sock but v1.5.2 of docker-compose
  # does not have to capability to mount individual files. Hence we mount the
  # entire folder in specific folder and specify it explicitly above.
  # This issue seems to be sorted in docker-compose 1.8.0 however that requires
  # Docker 1.10 and CI isn't at that version yet.
  volumes:
    - /var/run/:/host/var/run/
    #- /opt/gopath/bin/config/peer/:/opt/gopath/src/github.com/hyperledger/fabric/peer/
    #- /opt/gopath/bin/config/pbft/:/opt/gopath/src/github.com/hyperledger/fabric/consensus/pbft/

  # Use these options if coverage desired for peers
  #image: hyperledger/fabric-peer-coverage
  #command: ./peer.test --test.coverprofile=coverage.cov node start
membersrvc:
   image: hyperledger/fabric-membersrvc
   command: membersrvc
  # volumes:
  #   - /opt/gopath/bin/config/membersrvc/:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc/