###############################################################################
#
#
#    Redis section
#
###############################################################################
redis:
    # The address that the cli process will use for callbacks from chaincodes
    address: 0.0.0.0:6379
    pwd: 
    db: 0
    poolsize: 10
    batch:
        pending: 10
        matched: 10
        expired: 10
        cancel: 10

###############################################################################
#
#    REST section
#
###############################################################################
app:
    rest:
        # The address that the REST service will listen on for incoming requests.
        address:  0.0.0.0:7060
    
    adaptor:
        address:  0.0.0.0:7061

     # TLS Settings for p2p communications
    tls:
        enabled: false
        cert:
            file: testdata/server1.pem
        key:
            file: testdata/server1.key
        # The server name use to verify the hostname returned by TLS handshake
        serverhostoverride:

    events:
        # The address that the Event service will be enabled on the validator
        address: 0.0.0.0:7053
    
    admin:
        name: admin
        pwd: Xurw3yU9zI0l

    task:
        # redis 轮询时间频率
        polling:
            # 锁定挂单余额
            lock: 5
            # 撮合挂单
            match: 5
            # 处理撮合成功的挂单
            exec: 5
            # 查找过期挂单
            findexpired: 5
            # 处理过期挂单
            expired: 5
            # 处理撤单
            cancel: 5
    
    # conn Peer 连接peer方式 grpc/rest
    connpeer: rest

    # inner user
    users: lukas diego jim binhn alice bob assigner

###############################################################################
#
#    Chaincode section
#
###############################################################################
chaincode:
    id:
        path: github.com/wutongtree/exchange-chaincode/go
        name:

    # chaincode code type: golang  java
    type: golang